springdoc:
  api-docs:
    enabled: true
    #http://localhost:8080/api/api-spec    
    path: "/api/api-spec"
  swagger-ui:
    path: "/api/swagger-ui"
    #http://localhost:8080/api/swagger-ui
    #http://localhost:8080/api/swagger-ui/index.html?configUrl=/api/api-spec/swagger-config
    urls:
      - name: vms-services
        url: "/api/api-spec"

server:
  error:
    # include reason in error messages // TODO recheck for prod vmsbackend-db
    include-message: always

logging.level:
  ROOT: WARN
  com.sap.it: INFO
  #  org.springframework.web.servlet.mvc.method.annotation: DEBUG
  org.springframework.web: DEBUG
---
spring:
  profiles: cloud
  datasource:
    driverClassName: ${vcap.services.vmsbackend-db.credentials.driver}
    url: ${vcap.services.vmsbackend-db.credentials.url}
    username: ${vcap.services.vmsbackend-db.credentials.user}
    password: ${vcap.services.vmsbackend-db.credentials.password}
  jpa:
    hibernate:
      ddl-auto: update #(create, create-drop, validate, update)
    properties:
      hibernate:
        hbm2ddl.auto: update
      dialect: org.hibernate.dialect.HANAColumnStoreDialect
      format_sql: true
      show_sql: true
      enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.HANAColumnStoreDialect
    show-sql: true
---
# For Tests

spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop #(create, create-drop, validate, update)
    properties:
      hibernate:
        hbm2ddl.auto: update
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
      show_sql: true
      enable_lazy_load_no_trans: true
